services:
  tg-bot:
    build:
      context: .
    container_name: tg-bot
    restart: always
    env_file:
      - .env
    command: uv run python -m bot.tg_bot
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "5"